# ml_models/football/Dockerfile.ml_football
FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY bayesian_predictor.py .
# Assuming Flask app instance is named 'app' in bayesian_predictor.py and listening on port 5001
EXPOSE 5001
CMD ["gunicorn", "--bind", "0.0.0.0:5001", "bayesian_predictor:app"]
